spring:
  application:
    name: findex

  config:
     import: application-key.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/findex
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  task:
    scheduling:
      enabled: true

external:
  api:
    baseurl: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService

batch:
  sync:
    info:
      fixed-delay: 86400000
    enabled-index-data:
      fixed-delay: 86400000

logging:
  level:
    org.hibernate: INFO

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs